# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files and install all dependencies (including dev dependencies) for building
COPY package*.json ./
RUN npm install

# Copy the rest of the project files and build the TypeScript code
COPY . .
RUN npm run build

# Production stage
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install production dependencies only
COPY package*.json ./
RUN npm install --production

# Copy built assets from the builder stage
COPY --from=builder /app/dist ./dist

# Create a dummy OAuth2 credentials file so that the server can initialize
RUN echo '{ "installed": { "client_id": "dummy", "project_id": "dummy", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_secret": "dummy", "redirect_uris": ["http://localhost:4100/code"] } }' > .gauth.json

# (Optional) Expose port 4100 if needed for OAuth callbacks
# EXPOSE 4100

# Start the server
CMD ["node", "dist/server.js"]
